version: '3,8'

services:
  
  # Redis 数据库
  redis:
    extends:
      file: './redis/redis.yaml'
      service: redis

  # Nacos 分布式动态服务发现、配置管理和服务管理平台
  nacos:
    extends:
      file: './nacos-docker/example/standalone-mysql-8.yaml'
      service: nacos
    environment:
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 12345678 

  # Nacos-Mysql
  nacos-mysql:
    extends:
      file: './nacos-docker/example/standalone-mysql-8.yaml'
      service: nacos-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      
  # Mysql 数据库
  mysql:
    extends:
      file: './mysql/mysql.yaml'
      service: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: ruafafa
      MYSQL_PASSWORD: 12345678
        
  # 分布式对象存储
  minio:
    extends:
      file: './minIO/minio.yaml'
      service: minio
    environment:
      - MINIO_ROOT_USER=ruafafa
      - MINIO_ROOT_PASSWORD=12345678
