server:
  port: 23332

#Spring
spring:
  application:
    name: rcfun-article
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
      config:
        server-addr: 127.0.0.1:18848
        refresh-enabled: true
  config:
    import: nacos:rcfun-article.yml
